---
language: python
python: "2.7"

sudo: true

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # first run
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local

  # second run, verify idempotency
  - >
    ansible-playbook tests/test.yml -i tests/inventory --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Update test: pass' && exit 0)
    || (echo 'Update test: fail' && exit 1)

  # Verify service is running.
  - curl -I localhost:80

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
