---
go:
  - 1.10
python:
  - 2.7

services: docker

env:
  - distro: ubuntu1604
  - distro: ubuntu1804
  - distro: ubuntu1810
  - distro: debian10

before_install:
  - sudo pip install --upgrade pip
  - sudo pip install ansible
  - go get -v github.com/fubarhouse/ansible-role-tester

script:
  - ansible-role-tester full --distribution ${distro}

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
