---

language: go
install: true # https://arslan.io/2018/08/26/using-go-modules-with-vendor-support-on-travis-ci/
sudo: false

# Only clone the most recent commit.
git:
  depth: 1

go:
  - 1.x
python:
  - 2.7

services: docker

env:
  - distro: ubuntu1804
  - distro: debian10
  - distro: centos7

before_install:
  - sudo pip install --upgrade pip
  - sudo pip install ansible
  - go get -v github.com/fubarhouse/ansible-role-tester

script:
  - ansible-role-tester full --distribution ${distro}
  - ansible-role-tester full --distribution ${distro} --playbook tests/playbook-nginx.yml # test nginx stack

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
