---
- name: Load distribution specific variables
  include_vars: "defaults/{{ansible_os_family | lower }}.yml"
  tags:
    - zap_config

- debug:
    var: zap_port

- name: Run OS specific tasks.
  include: "{{ansible_os_family | lower }}.yml"


# NOTE: our keys get alphabetized, so 'expand' is lost in depths.
# This means if you want to manage config by hand, you're better off
# not using the {{ zap_config }} option
- name: Write zap config to {{ zap_config_location }}/c.yml
  copy:
    content: "{{ zap_config | to_nice_yaml(indent=2) }}"
    dest: "{{ zap_config_location }}/c.yml"
  when: zap_config is defined
  tags:
    - zap_config
  notify:
    - "restart zap {{ ansible_os_family|lower }}"

- name: Write zap header to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "### Zap Shortcuts ###"
    state: present
    insertafter: EOF
  when: zap_config is defined
  become: yes
  tags: zap_dns


- name: add shortcuts to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '{{ zap_host }} {{ item }}$'
    line: "{{ zap_host }} {{item}}"
    state: present
    insertafter: "### Zap Shortcuts ###"
  when: zap_config is defined
  with_items: "{{ zap_config }}"
  become: yes
  tags: zap_dns
  notify:
    - "start zap {{ ansible_os_family|lower }}"


# convenience helper - if dnsmasq installed and on debian, attempt a reload
# if it's not running we ignore the error.
- name: Check if dnsmasq is installed
  when: ansible_os_family == 'Debian'
  command: dpkg-query -l dnsmasq
  register: dnsmasq_check
  changed_when: false
  tags:
    - zap_dnsmasq

- name: Attempt reload of dnsmasq
  when: ansible_os_family == 'Debian' and dnsmasq_check.rc == 0
  service: name=dnsmasq state=reloaded
  ignore_errors: yes
  tags:
    - zap_dnsmasq
