---
- name: restart zap debian
  service: name=zap state=restarted
  become: yes

- name: start zap debian
  service: name=zap state=started enabled=yes
  become: yes

- name: restart zap redhat
  service: name=zap state=restarted
  become: yes

- name: start zap redhat
  service: name=zap state=started enabled=yes
  become: yes

- name: restart zap darwin
  command: /usr/local/bin/brew services restart zap
  become: "{{ zap_standalone }}"

- name: start zap darwin
  command: /usr/local/bin/brew services start zap
  become: "{{ zap_standalone }}"

- name: reload nginx
  service: name=nginx state=reloaded
  become: yes
